server:
  port: 8080

spring:
  application:
    name: AUTH-SERVICE

  datasource:
    url: jdbc:mysql://auth-db:3306/auth_db?createDatabaseIfNotExist=true
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  cloud:
    compatibility-verifier:
      enabled: false

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka
  instance:
    prefer-ip-address: true
    hostname: auth-service

management:
  endpoints:
    web:
      exposure:
        include: "*"

  tracing:
    sampling:
      probability: 1.0

  zipkin:
    tracing:
      endpoint: http://zipkin:9411/api/v2/spans   # remove if not using zipkin

springdoc:
  api-docs:
    path: /v3/api-docs
